# Generated by Django 4.0.5 on 2022-07-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_postview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='view_count',
        ),
    ]
