# Generated by Django 4.0.5 on 2022-07-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_postmodel_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
